# Generated by Django 4.2.6 on 2023-11-01 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_district_result_alter_region_month_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='month_choice',
        ),
        migrations.RemoveField(
            model_name='region',
            name='month_result',
        ),
        migrations.CreateModel(
            name='RegionMonthlyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_choice', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10, null=True)),
                ('result', models.FloatField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.region')),
            ],
        ),
    ]
