# Generated by Django 4.2.6 on 2023-11-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_region_month_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionmonthlyresult',
            old_name='month_choice',
            new_name='month',
        ),
    ]
