# Generated by Django 4.2.6 on 2023-11-01 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmonthlyresult',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.month'),
        ),
    ]
