# Generated by Django 4.2.6 on 2023-11-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_regionmonthlyresult_month'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegionMonthlyResult',
            new_name='RegionsMonthlyResult',
        ),
    ]
