# Generated by Django 4.2.6 on 2023-11-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_rename_regionmonthlyresult_regionsmonthlyresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegionsMonthlyResult',
            new_name='MonthlyResult',
        ),
    ]
