# Generated by Django 4.2.6 on 2023-11-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_rename_regionsmonthlyresult_monthlyresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyResult',
            new_name='RegionMonthlyResult',
        ),
    ]
